name: Auto-release
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r src.zip . -i *
      - run: mkdir out
      - run: mv src.zip out
      - run: ls out
      
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: master
          files: out
          commit-message: "auto-release"
          force-add: true
          force-push: true
