name: Auto-release
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r src.zip . -i *
      - run: mkdir out
      - run: mv src.zip out
      - run: ls out
      
      - name: Push new files back to master.
        uses: mikeal/publish-to-github-action@1.0.0
